apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: arturo-llm-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi    
      storageClassName: standard  # clase estándar en GKE
