apiVersion: v1
kind: Namespace
metadata:
  name: arturo-chaos
  labels:
    managed-by: aiops-agent
    project: uniovi-ai-infra-agent
    environment: chaos
    created-by: arturofernandezg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-crashloop-target
  namespace: arturo-chaos
  labels:
    managed-by: aiops-agent
    project: uniovi-ai-infra-agent
    environment: chaos
    created-by: arturofernandezg
    chaos-type: crashloop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-crashloop-target
  template:
    metadata:
      labels:
        app: chaos-crashloop-target
        chaos-type: crashloop
    spec:
      nodeSelector:
        guaranteed: "true"
      tolerations:
      - key: "guaranteed"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: crasher
        image: busybox:stable
        command: ["/bin/false"]
        resources:
          requests:
            memory: "8Mi"
            cpu: "10m"
          limits:
            memory: "16Mi"
            cpu: "50m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          allowPrivilegeEscalation: false
      restartPolicy: Always
